name: Toy Kernel CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt update && sudo apt install -y build-essential qemu-system-riscv64

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: riscv64gc-unknown-none-elf
          components: rust-src

      - name: cargo build it!
        run: cd os ; make run ;
