name: Toy Kernel CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install deps
        run: sudo apt update && sudo apt install -y build-essential rust cargo

      - name: Add Rust target
        run: rustup target add riscv64gc-unknown-none-elf

      - name: Add Rust component
        run: rustup component add rust-src

      - name: cargo build it!
        run: cargo build
